// Generated by the asset pipeline — 24px inline previews, one per image.
// Regenerate rather than editing by hand.
const blurMap = {
  "/img/about-1.webp": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACwBACdASoYABAAPulgqE0pJaOiMAgBIB0JYwCdAYwc7WpD+4PxQXyVLkvK37/gAP22cpEIyhlkK6omAQ8CjKLIyBat+WqLE5cBuQgDTPEIXoCm0cywep/X9AgjkDuiNQjoBYQTCrWJJJDsg09o3IHjy9nnW8x4H8S4jjLm0X8mfKX2dpsaysc3dx2g2opq/xUnK0t2UfEpP2nWhJhyjzLxnL+SSIVAAAA=",
  "/img/about-2.webp": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAwBACdASoYABAAPulgqE0pJaOiMAgBIB0JbACdABjTWwNSU77t4ZWUsZAA/vKyCabceObrzwLF7KglXzK5hm1kOOijMWn2Qp6C6oEAuHRc/kV+2TUip5hpaQuOIcdz3BJyu8D3qZS8YcsP2WSDvXrAhyege50XansJmC7jK6MGwDPjWSSy7bFhs6JAZNt+gnvDgAAA",
  "/img/cta.webp": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwBACdASoYABQAPuFapk0opSOiN/VYARAcCWUAuwAQ704f+Yrwi+gpCR87yVh7BHAA/u/JNHbLnvFr2ne3vMPRhT46g/MWRGxw6cPP2mdFRi3uZh+QY4IChIvulMjbycIbhcAdeoYijctuPzGgAA==",
  "/img/ev-1.webp": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAADQBQCdASoYAB4APulkqU8pJaOiKA1RIB0JbACxG3WGdKWYfzvOThMl69StreW42Z41F1lhz6VoAP72SJ8om3nm8L5Pm/v7OI09FcOmDpvU0iLR79FOafxW/z8ZEKrfzsMpjxALV0BxOjGKwRzjYSSTc3OG3fuUWLlqiMPvfqqpmDwxDEhS6iUHZbLdNYiZKvNti1z/PgDPXrW2GE9V2P83QB6Ujk3cIhQnE2+Jc0QmK8qH+oYgr0tx3hbPhSUvmTnWS+RCeZAAAA==",
  "/img/ev-2.webp": "data:image/webp;base64,UklGRvYAAABXRUJQVlA4IOoAAAAQBgCdASoYACAAPulsrlGpJaQiqAgBIB0JZACdMxglzDz7iAhGXwMmOcgpZZFvGZe1IapDuG6mfYAAzibjUpBp06hy+HuvTMdBz8wfkH/48NpiuPJh6jgPnLrviVTbMpCE9PKzNPVQg6M6+v/hyzPBJglFextLecU3xRKmqS0vVoy2a+okjezPxqdqzN2/N+vvOt2o/Nrm439J100AGWFka2ZZMe1QrWX1cvjw+UfzInBzVUV0dItafDq/bP5MsvfS1LWg1gJCY6G0gHoyXGbpiLnFBvQm22OIOJpjvJ30Z8/2WlCgA/wuxAA=",
  "/img/ev-3.webp": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoYABAAPuleqE0pJSQiMAgBIB0JYgCw7CP/K+Q22lFxCDMRLakAAP7s2rTCuYqndDVC9aB6xWqNhbSVQ5F1uy/9/BUjtAaFEwug4ec9sDOLkxUAoTWqp7grY6uRa4+U6E9rHMxn+g99L0pW5Bi7LQTWdUC+Jp7AcQsPACDvJmFQEIbtMJj1GJpLuGtP4dakiKT+uXf4AAA=",
  "/img/ev-4.webp": "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAACQBQCdASoYAB4APuliqU6pJaOiKA1RIB0JZAC/OYwTyfhWCbxblVTCs1RYshhECqjiSpjpAAD+5xfR9dTd5kEqmlNQTPpw+UGj+mC8wANIdWprBIgdV8IFUWaAABJLO6EOqqqPmbHwLUWq9pg+fk32vlIt/HUp+Wk87EfrZ2ZjbRf+/1vZTu48qy2Qoxj5oUS0RU/zNwjBP9G5xn3RUZZbrfqAGnBVFKnXnOAMfBx8M6upujOSnBky3ej7+NSK8VFHKyLLjE1WYOOneQySApArJJpOFpDNClh392fz3Elpi0nNrgdkZMP/bHKNV8UBk/dyjso/tjQOCPkbTlCCcO3EZ8XT6hAA",
  "/img/ev-5.webp": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAQBQCdASoYABgAPtlcqE0oJSQiMAwBABsJaACdMoR+J/aCarE2rzXHtRdOc+AeyGLAAPcEJk8jldizvTRy6RANj2ZOp4XP9h83BZvAWr4hu/i34CzQ3HXJrF1ab0B2zF1nUUPLmLhn/NKd1ImXASFd0grWwNZje4/yJO5TFp8WwpASWpOHh9SSc02pBUGjmtNa9HwUfY2c8+olDjuro4j7Bc4HWKqAE8QAAA==",
  "/img/ev-6.webp": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYAA4APuleqE0pJSQiMAgBIB0JZACdMoMulE5Hdljn63KiWb88AADNYgAbGa0GmRvOtN/0DdxhEgYzV1/Y9WkMSWsx9roceXFd1Gcsk2Pd57Fokc0ERI/LSTRlIxKu4RXuXJaN68leq/CW70i5A58HTimLfH4pFfvyrW3gQcAAAA==",
  "/img/hero-1.webp": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoYABAAPuleqE0pJSQiMAgBIB0JZgCdACHIvVjnpsZHvP7AAP7Li8DCfmvPLwYgNcxryEIGEq5s/COIj661k1fZ3s4/DcQx7MvxIt2mMMRf0bqS6sfuMncChN0kE81zLkbYGN8hWiwAAA==",
  "/img/hero-2.webp": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoYACAAPulgq0+pJSOiMBgIASAdCUAABc7J5+vE6xEBDfyVtNEAAP7eqXvIvsF/A/eWWdLu2rgCiD70xppvXPgx0wKilfDtXf5Ld6+MuWGXUF2T9t+Ke66x/113jS9H/xF087Fi/6tHpuTRGo9bf1EabqC74VQVCaEYjnfqQKcCHeTPjFaAAdWGMigTGuglPiOua1ocAAA=",
  "/img/hero-3.webp": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYABAAPulgqE0pJaOiMAgBIB0JZQCdAB0lpv0hX//MTEl5AAD+8N+B4tuuajX6WSsgMtgbvI7MwAVpmPLkiqHAjvPuTMCXZNRphr9/kOJm7+ID28eB2vFOm8xxyY7/UQl7GmNcmRoVXaHE9J92mZxpIfBc0C9hTwkFtc1kisVkduHx7sAAAA==",
  "/img/p-blocks.webp": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQBACdASoYACQAPuFSo00opCMiNVv4ARAcCWkAAEqUsjyhmkH6K4YYnwVFGI/DAAD+3uwgMuNC4duGPQiejSnVlcDlmBf2k5XRkC/U4AAAAA==",
  "/img/p-bricks.webp": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAwCdASoYABAAPulgqU2pJaQiMAgBIB0JYwCw7BDl0A0DhIAA/RLwWbEJSh1SMMIxk/J+l4JvoftA9QuNre/JZVgqtOc8CxTT32ntoBoy03taqFVYuSNzGKagt8uGAAA=",
  "/img/p-cement.webp": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoYABAAPulgqE0pJaOiMAgBIB0JZwDCgYw6yU+5FlMXLHpAAAD+v7nrgYU0wgOXKtqix0YeudqNah82JToqGd0/16lxwReejXrzN/IjmC0jjCCJK3iXg4XaLat5iWY3v9R6uZaiX/9AMuG1oA2suUJ+rPDW74Jx2q5REvsBlTIA8YAA",
  "/img/p-doors.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAwCdASoYABAAPulgq00pJaQiMAgBIB0JYwCdACHf1m1pGe2FAcAA/uyvpeip6ii5Bl/SRAkEzN1AakSDH2XFR4C9EAAA",
  "/img/p-hardware.webp": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwBgCdASoYACQAPuloq06pJiQiKrgMASAdCWMAqS1BVyETzAvjiRjcSspeiqtbIvMrCNngQi7rVwyao1jmgAD+72Hspkc7pjLYOj+4eK1WqtiMd6ukxmBc9sWgKzRz3lRZFxKK7teJWo8Rdk+jdxzjee0zyiNkWeeq1V8+Dtcx7Vu+vgguaVImlHcu7th7n7wRYvYpGHkts9kKnIcAAA==",
  "/img/p-msand.webp": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADwBQCdASoYACQAPuluq1IpJiOipWsxIB0JZQC/OC5ulbXoMxi+yeYfp35uG44WvEZpyH3DJ/1hAAD+3q/VmYPU63GnXk6REztXpjg9aDLK7hMiEpsEwy/cnk8du5ohsDM3woli1sR1hn/3zD7bERwTfroCJj6Z2gbBrub94fmGcfjY3vf0z+x/odCnNYBJeUmelZvAmWw5UREYrx/aIl3HVlFRYKbVJdFAAA==",
  "/img/p-paints.webp": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoYABAAPulgqE0pJaQiMAgBIB0JbACsLwAB2zUH00uUFE67MgAA/vDUtOp/j80gh5KUy2buF2/j9w1cG5Gy3RtWuksM2/I+jt1hojXHpfiBIOneiC2+xN+0xRnfRS7Hnnqe+eSo41eveOwo2CWWgeV6O1AAAA==",
  "/img/p-psand.webp": "data:image/webp;base64,UklGRlIBAABXRUJQVlA4IEYBAACQBwCdASoYACQAPulmq1ApJSOiqqgBIB0JZQC7M/W6BsnXK94gJjJwpIevzectzRBLSBDJX1BKjEbW5NelrcXFwjppoCAA/uTplHfCKZRT/x5fcXkghinO2vlWR3gsn2ftAOQC5nVOdGKYpvnZziwjoBI8pLnaGPT/XYrlpVInICH8kg555af3rINKrQ1zxR6g9OG0QFa39p5+wSkOveo3SjXd5NQxE9q/rPftMLjpS2ZSmzeY27b2gtWfnZ4TAaBc/3Ul9rsE9w//ytPpfqXEkUV4CC7IYtJtsDt+5EfpeMzh6XRG9j/aEvzhU3awYgAuKzaHjf2HMP4ATZ1mGX65nGVdfV9g7XVdc79Pri+Rx3pion5d8ZIlkLcvv5bGaH0kztNsGX5Alyqk40WEUbRS1CeFQAtdUD/7jmo4eVZvYAGJNmAAAA==",
  "/img/p-rings.webp": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoYABAAPuleqE0pJSOiMAgBIB0JQBWAMW0b7QHhOfVQru3T9ucAAP7qhILz9CAMYulTAZ/5ZrqvlR7VcHvTo1h6c7UubP1LrRv1q7ez0GIP1371wydeCQ85/xEkPHGGNRjN6I0DRneZnEu9ktDZUlSN7gAJ8gBT1gSqhot2HNcYJNSI13AAAA==",
  "/img/p-tmt.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAwCdASoYABAAPulgqE2pJaOiMAgBIB0JZwAAelasp4gAAP7uHr6cgXgnZr8X4K25fHtkdcsX/34IehhxLAk4a2UaGvcSuVY5RDOFVKm751AV+0U4REAA",
  "/img/p-waterproof.webp": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAAAQBwCdASoYACoAPuFcpE0opSOiNVQMARAcCWcAzfwLRidOZX+OmN8nwLQLsqAl+VfX4a+SvW7VhjZ36NdGLZGVwAD+UfJ/gj1YdNgP56GrrKoYAQpbEOPsNuGn1QHxU3czBZ3x95TxuwoN2PSMmZZoeTzWz0FJAQGbJfOfnrkPqAZnrJZTx6GjLW2XYZrWx7YngT/qfWvo8N4XxF5vlyYiAyhU3aNLPQ20ZGkMg04AAA==",
  "/img/p-wire.webp": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoYABAAPuleqE0pJSOiMAgBIB0JaQAD4/IvsPfXlO+P6GcAAP7xf5D2v+qf9Pe5q9M0kwfLjT1S5QiDGgV8yB8JouOwcMyEoPRSAaImAP/+PpIPLj1l7hnXfTo+L/NN/4K6E6L3xO4RHfdKD2QL/XYydbkkKp8whHUGTzltLYtwue6m4NXtciD/qyKAAA==",
  "/img/texture-concrete.webp": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwBQCdASoYACQAPuliqE4pJaOiKqwBIB0JaQDQGAnxr9P3+AGFk6X3TNq16FUuUf18iH+02A10AAD+uw9ZHTW/0W45uixQB/uZD5QVapjITCtbOwP93KyEontLaP5X9/sfsK+aPKQH4B1tlaIeVr/EBnmZJuf9bLcSUuQ6+lj0a2+c8OOvEFP25eMlzOp2v2vSIA5vcUnXeHAAAAA=",
  "/img/why-1.webp": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoYABAAPulgqE0pJaQiMAgBIB0JZQAAW9ODSGEbW8LZlAD+7LBMga6pgrZQXGmRkNzZvYg7U0Aig278yscnK8v0p/LJ+C2f83dompAHunMA67qQ6ceqdUihkWqGEUpTkvu6+4YiqNjtK3ThNvosAA==",
  "/img/why-2.webp": "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAAAwBQCdASoYABIAPuloqlCpJaOiqAqpIB0JZQC7AYuGaN8znz0zaBPwWNQiSZvnPigvAADyo7OlrDwDNkP7MvS9v2fQXkACJq8UV9PO71L+nnsHqvXqrNy2kDT/a5sQMnH4mZFozn2owMrChQTueT/LNX3hPsSyD9dGo/hifBHhNyOfUoAMh7PnuekQBMgTgZ9ojoUTxd3lnUPrBzijYLUUQtocTWzxExaHBh39RA8oUimBdAnlAN7g0OF9mMWbE5kpe9ruUok4zVA3YTa0vBFfVWKcpZEx2qs34Z1K1N0HpRgEMr/wh8GB4qfO//IVOrnWP+GqbBfyuc/9AAA=",
  "/img/why-3.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoYAA4APulgqU2pJaQiMAgBIB0JQBOgAo7omOqrVjDoAPnjf1QpWPOwV6x8EBC9qtx51KQ4WPWTv7tyU6hy6mOm3wQUe92m6LiLi5vgvDWqJ0zKuhRUAAAA",
  "/brands/agt-logo.png": null,
  "/brands/b10.png": null,
  "/brands/b11.png": null,
  "/brands/b12.png": null,
  "/brands/b5.png": null,
  "/brands/b6.png": null,
  "/brands/b7.png": null,
  "/brands/b8.png": null,
  "/brands/b9.png": null,
  "/brands/berger.png": null,
  "/brands/dalmia.png": null,
  "/brands/ramco.png": null,
  "/brands/ultratech.png": null
};

export default blurMap;

export const blurFor = (src) => blurMap[src] || undefined;
