/**
 * Asset pipeline.
 *
 * 1. Encodes source photographs into pre-sized WebP in public/img
 * 2. Regenerates lib/blur.js with a 24px inline preview for every image
 *
 * Needs ffmpeg once:   npm i -D ffmpeg-static
 * Then:                npm run images
 *
 * Drop full-resolution originals (.jpg/.png/.webp) into assets-src/ and run.
 * If assets-src/ is absent, it leaves the WebP files alone and only rebuilds
 * the blur map — which is what you want after hand-swapping an image.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(root, "assets-src");
const IMG = path.join(root, "public", "img");
const TMP = path.join(root, ".image-tmp");

let FF;
try {
  FF = (await import("ffmpeg-static")).default;
} catch {
  console.error("ffmpeg-static is not installed.  Run:  npm i -D ffmpeg-static");
  process.exit(1);
}

// Width and WebP quality per filename prefix. Sized to the layout, not to the
// monitor — nothing here is ever displayed larger than these numbers.
const profile = (name) => {
  if (name.startsWith("hero")) return [1800, 76];
  if (name.startsWith("cta")) return [1800, 72];
  if (name.startsWith("why")) return [1400, 72];
  if (name.startsWith("about")) return [1300, 74];
  if (name.startsWith("texture")) return [700, 58];
  if (name.startsWith("ev")) return [800, 72];
  if (name.startsWith("p-")) return [1000, 70];
  return [1200, 74];
};

fs.mkdirSync(TMP, { recursive: true });
fs.mkdirSync(IMG, { recursive: true });

const run = (args) => execFileSync(FF, [...args, "-loglevel", "error"]);

// ---- 1. encode originals, if any were supplied -----------------------------
if (fs.existsSync(SRC)) {
  const originals = fs
    .readdirSync(SRC)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f));

  for (const file of originals) {
    const name = file.replace(/\.[^.]+$/, "");
    const [w, q] = profile(name);
    const out = path.join(IMG, `${name}.webp`);

    run([
      "-y", "-i", path.join(SRC, file),
      "-vf", `scale='min(${w},iw)':-2:flags=lanczos`,
      "-quality", String(q),
      "-compression_level", "6",
      out,
    ]);

    console.log(`encoded  ${name.padEnd(18)} ${w}px q${q}  ${(fs.statSync(out).size / 1024).toFixed(0)}K`);
  }
} else {
  console.log("no assets-src/ — keeping existing WebP, rebuilding blur map only\n");
}

// ---- 2. rebuild the blur map ----------------------------------------------
const blur = {};

for (const file of fs.readdirSync(IMG).filter((f) => f.endsWith(".webp"))) {
  const name = path.basename(file, ".webp");
  const tiny = path.join(TMP, `${name}.webp`);

  run([
    "-y", "-i", path.join(IMG, file),
    "-vf", "scale=24:-2:flags=area",
    "-quality", "42",
    tiny,
  ]);

  blur[`/img/${file}`] =
    "data:image/webp;base64," + fs.readFileSync(tiny).toString("base64");
}

const out = `// Generated by scripts/images.mjs — 24px inline previews, one per image.
// Run \`npm run images\` to regenerate rather than editing by hand.
const blurMap = ${JSON.stringify(blur, null, 2)};

export default blurMap;

export const blurFor = (src) => blurMap[src] || undefined;
`;

fs.writeFileSync(path.join(root, "lib", "blur.js"), out);
fs.rmSync(TMP, { recursive: true, force: true });

const total = fs
  .readdirSync(IMG)
  .reduce((n, f) => n + fs.statSync(path.join(IMG, f)).size, 0);

console.log(`\nblur entries: ${Object.keys(blur).length}`);
console.log(`public/img total: ${(total / 1024 / 1024).toFixed(2)} MB`);
